name: e2e-tests
on:
  workflow_dispatch:
  schedule:
    - cron: '10 5 * * *'
  push:
    branches: [ main ]
jobs:
  cypress-run:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          start: npx cypress run
          browser: chrome