name: Scheduled all cypress tests 
on:
  workflow_dispatch:
  schedule:
    - cron: '10 5 * * *'
jobs:
  cypress-run:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - name: Cypress run
      uses: cypress-io/github-action@v6
      with:
        build: npm run build
        start: npm start
        browser: chrome
     